export enum ActivityRecordEvent {
  EVENT_CREATE = 1,
  EVENT_UPDATE = 2,
  EVENT_DELETE = 3,
  VOLUNTEER_SWAP_REQUEST = 4,
  VOLUNTEER_SWAP_COMPLETE = 5,
  VOLUNTEER_SWAP_CANCEL = 6,
  EMAIL_ACCOUNT_CREATE = 7,
}
