import { AccessControl } from 'accesscontrol';

export enum Roles {
  ADMIN = 'admin',
  VOLUNTEER = 'volunteer',
  DEFAULT = 'default',
}

const ac = new AccessControl();

ac.grant(Roles.DEFAULT)
  .createOwn('user')
  .readAny('user')
  .updateOwn('user')
  .readAny('course')
  .readAny('project')
  .readAny('event')
  .readOwn('user')
  .readOwn('file')
  .readAny('file-field')
  .createOwn('file-attachment')
  .readOwn('file-attachment')
  .deleteOwn('file-attachment')
  .createOwn('event-registration')
  .readAny('event-registration')
  .readOwn('event-registration')
  .updateOwn('event-registration')
  .deleteOwn('event-registration')
  .createOwn('file')
  .readOwn('file')
  .readAny('volunteer-job')
  .readAny('volunteer-work')
  .createOwn('membership')
  .updateOwn('membership')
  .readOwn('membership')
  .grant(Roles.VOLUNTEER)
  .extend(Roles.DEFAULT)
  .createOwn('volunteer-registration')
  .createOwn('volunteer-work')
  // TODO .readAny('user')
  .grant(Roles.ADMIN)
  .extend(Roles.VOLUNTEER)
  .readAny('activity-record')
  .createAny('system')
  .readAny('system')
  .updateAny('system')
  .deleteAny('system')
  .createAny('file')
  .readAny('file')
  .updateAny('file')
  .deleteAny('file')
  .createAny('file-field')
  .updateAny('file-field')
  .deleteAny('file-Field')
  .createAny('file-attachment')
  .readAny('file-attachment')
  .updateAny('file-attachment')
  .deleteAny('file-attachment')
  .createAny('event-registration')
  .updateAny('event-registration')
  .deleteAny('event-registration')
  .createAny('account')
  .readAny('account')
  .updateAny('account')
  .deleteAny('account')
  .createAny('course')
  .updateAny('course')
  .deleteAny('course')
  .createAny('event')
  .updateAny('event')
  .deleteAny('event')
  .createAny('project')
  .updateAny('project')
  .deleteAny('project')
  .createAny('user')
  .updateAny('user')
  .deleteAny('user')
  .createAny('volunteer-work')
  .updateAny('volunteer-work')
  .deleteAny('volunteer-work')
  .createAny('volunteer-job')
  .updateAny('volunteer-job')
  .deleteAny('volunteer-job')
  .createAny('email')
  .createAny('membership')
  .readAny('membership')
  .updateAny('membership')
  .deleteAny('membership');

export default ac;
