name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      directory: "~/app-dev"
      branch: "dev"

    steps:
      - name: Pull Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.directory }}
            git checkout ${{ env.branch }}
            git pull

      - name: Upgrade Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.directory }}
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            yarn

      - name: Run Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.directory }}
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            yarn server mikro-orm schema:update -r --fk-checks

      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.directory }}
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            yarn server build
            yarn client build

      - name: Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.directory }}
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pm2 restart server-dev
            pm2 restart client-dev
